### ISSUE TITLE
Canle de Spotify

### ISSUE THREAD

**Issue by barcia** [barcia/ngal#12]
Vin que nalgún caso hai engadido en Spotify a url de un podcast. Descoñecía un pouco o obxetivo de esa canle, pensei que sería para poden engadir playlists ou así. Se é para definir a plataforma de un podcast, eu creo que eso debería estar dentro da canle de podcast, porque de feito o ideal sería que houbese varias plataformas ahí: Por exemplo algo así:

```yaml
podcast:
  feed: url_feed
  platform:
    spotify: url_spotify
    apple: url_apple_podcasts
    google: url_google_podcasts
    ivoox: url_ivoox
    pocket_casts: url_pocket_casts
```

**Comment by oscarotero** [comment]
Bueno, inicialmente era unha url a unha playlist (a newsletter "Mamá, non teño un can" ten unha playlist na que cada semana engaden unha canción nova). Logo tamén o usei como url de podcast porque Spotify tamén ten soporte para iso.
Non sei moi ben cal pode ser a solución.

Quizáis, para casos nos que pode haber 1 ou n url, podemos facer o mesmo que cos autores, permitir un string ou un array. 

Exemplo con un:
```yml
podcast:
  feed: https://exemplo.com/rss.xml
  url: https://exemplo.com
```

Exemplo con varios:
```yml
podcast:
  feed: https://exemplo.com/rss.xml
  url: 
    - https://exemplo.com
    - https://open.spotify.com/blablabla
    - https://www.ivoox.com/blablalba
```

E xa pola url xa sabemos se é unha plataforma tipo spotify ou ivoox, ou pode ser unha web propia. Non sei, digo por non facer algo demasiado estricto. Date conta que, independientemente do número de urls que teña, só imos usar unha url de feed para o contido.
