### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by oscarotero** [barcia/ngal#5]
Boas. O outro día vin o proxecto este e pareceume unha idea estupenda. Eu pensara hai tempo en facer algo en plan [awesome](https://github.com/sindresorhus/awesome) pero a túa idea de que sexa unha API autoactualizada é moito mellor.
Se precisas axuda con algunha cousa, estaría encantado de colaborar.

**Comment by barcia** [comment]
Ola! grazas!! O do awesome tamén é boa idea, si! E seguramente máis sinxela… 😅 esto veu a raíz de que quería publicar na miña web unha páxina con unha listaxe de creadores e creadoras en galego, pero que molaría máis se a maiores eso incluíse cousas como por exemplo o último episodio dos podcast, o último vídeo das canles de YouTube, etc. Así incluso podería ser un lugar ao que a xente fose recurrentemente.

Á súa vez, vendo que ía crear unha especie de API interna para usar, pois ocorreuseme a idea esta de facer a API como un proxecto independente por se o quería usar alguén máis, e sobretodo para aprender eu un pouco, que nestas cousas de traballar con API's e e tal estou algo verde… e para xogar tamén un pouco con cousas como Next.js, Strapi, ou cousas do estilo, que me gustan bastante. 

E si, por suposto seguramente precise axuda, que como che digo, nalgunhas cousas estou bastante verde, pero ademáis de iso calquera idea nova ou distinta que teñas é benvida. 

Moitras grazas!

**Comment by oscarotero** [comment]
Asi como idea, imaxínome un repositorio aberto onde calquera poida engadir cousas (unha canle de youtube, un podcast, un blog, etc), e logo se forme unha web estática onde velos (e buscalos) ou unha api onde consumilos.
Algo parecido a como fan na web de jamstack.org (https://github.com/jamstack/jamstack.org/tree/main/src/site/generators), e que cada novo contido teña o seu arquivo propio, así é máis fácil facer pull requests, non ter conflictos e eso.

Quizáis incluso a web pode estar nun repositorio diferente á api... en fin, estou pensando en voz alta.

Logo, o da actualización automatica pódese facer con github actions, creando unha acción que se execute diariamente ou asi.

**Comment by barcia** [comment]
Si, eso era mais o menos o que tiña planeado. Por exemplo, os podcasts que engadín teñoos nun arquivo onde engado o feed, e onde calquera podería colaborar: [data/podcasts.js](https://github.com/barcia/ngal/blob/main/data/podcasts.js). E a partir do feed recupero a información de cada podcast.

Para as canles de YouTube e Twitch, quería facer algo parecido. Ter só a ligazón da canle e coa API de cada unha das plataformas recuperar a información que se poida.

**Comment by oscarotero** [comment]
Entendo. Supoño que xa estas ao tanto, pero bueno, para os podcasts, telos todos aqui: https://podgalego.agora.gal/
E para canles de youtube, moitas delas estan nos recopilatorios da Lobeira Today (https://www.youtube.com/c/ALobeiraToday/videos).

Para meter os contidos, teño algunhas suxerencias, a ver que che parecen:

- Eu non gardaría os contidos separados en módulos de javascript separados por formato, porque pode haber casos multiformato (por exemplo MBA Mal ten [podcast](https://podgalego.agora.gal/mba-mal/) e tamén [canle de youtube](https://www.youtube.com/channel/UCgKg2cDI9GCxd-dHMBPMv2w)).
- Propoño ter un arquivo por cada contido nun formato máis fácil de editar, como markdown ou yaml. Por exemplo `mba-mal.md`, que podería ter unha descripción e logo outros valores como category, feed, title, etc. [Un exemplo con cómo fan en jamstack](https://raw.githubusercontent.com/jamstack/jamstack.org/main/src/site/generators/20ful.md). Deste xeito, cada pull request engadiría un novo arquivo, en vez de editar sempre o mesmo (que pode levar a conflictos de git).
- Logo usando un xerador de páxinas estáticas, crear páxinas en html, ou json para a API, un RSS feed con novidades, etc.
- Como cada contido estaría correctamente etiquetado, logo póndense facer filtros en plan (amosar só canles de youtube, ou só newsletters, ou calquera formato coa temática videoxogos, etc).

En fin son só ideas, se non che encaixa co que tiñas pensado, non hai problema :)

**Comment by barcia** [comment]
Si, dese tipo de recursos teño algúns gardados que fun acumulando dende fai tempo. Teñoos anotados na [Wiki](https://github.com/barcia/ngal/wiki)

E do resto de puntos que comentas a verdade é que creo que concordo con todos 🙂 Sobretodo vexolle as vantaxes ao que comentas de un arquivo para cada elemento.

Onde teño dúbidas é onde dis o do multiformato. Propós que cada arquivo poida ser multiformato e ter varias canles do mesmo creador? 🤔. Non sei se eso pode ser algo lioso se alguén quere engadir un novo creador, e ademáis eu creo que eses casos van ser moi puntuais, non? Ao mellor, aínda que estén en arquivos separados, pódese establecer un campo para relacionar unha canle con outra.

E que eu cando pensei o de separar por plataformas (ou formatos) é pola información que podemos obter automáticamente de cada una deles, por exemplo:
* Das newsletters temos a URL, pero non podemos obter ningunha información automáticamente, e para engadir cousas como _descripción_, _etiquetas_, _autor_, ten que ser manualmente.
* Dos podcasts podemos engadir só a ligazón do feed, e obter cousas como _título_, _imaxe_, _descripción_, pero poida que queiramos engadir manualmente cousas como as _tags_.
* E de plataformas como YouTube ou Twitch eu tiña a esperanza de que engadido só a URL da canle poidamos obter toda a info da mesma.

Por eso, como creo que cada tipo de contido podería ter uns campos distintos, igual podería ter sentido que estivesen en lugares separados.

Outra opción pode ser establecer uns campos xenéricos para todas as plataformas e poñer todo xunto. Non sei, a verdade.

**Comment by oscarotero** [comment]
Vale, non vira a wiki :)

En canto ao do multiformato, si, que o mesmo creador poida ter todas as súas canles no mesmo arquivo. Como unha especie de perfil. Non sei se hai moitos casos, pero por exemplo A lobeira today, ten canle de youtube, de twitch, twitter, páxina web (https://alobeiratoday.gal/) etc. E o mesmo pasa con outros creadores como Pradorua, que ten canle de youtube, instagram e tiktok. Non sei, habería que pensar nun formato que poida encaixar. Por exemplo:

```yml
title: Nome do proxecto
author: Nome do autor
youtube: url
instagram: username
tiktok: username
web: url-paxina-web
topics:
  - topic-1
  - topic-2
podcast:
  feed: url-do-feed
newsletter:
  title: titulo da newsletter
  feed: url-do-feed
```

Algúns proxectos terán máis info, outros menos. Non sei que che parece. Ollo, esto sería a nivel de proxecto. Se o mesmo autor ten varios proxectos, pois habería varios arquivos.

**Comment by barcia** [comment]
Ok, entendo… planteas que cada un dos arquivos sexa para un **proxecto**, non para un **creador**. A verdade é que tenme boa pinta. Ademáis, tal e como plantexas, cada unha das canles pode ter igualmente un formato distinto, que era o que planteaba eu.

Subir agora uns cambios ao repositorio con unha plantilla do que comentas… a ver que che parece así.

**Comment by oscarotero** [comment]
Paréceme moi ben, moi ben estructurado.
Un detalle, os guións en yaml son para crear un "array" de elementos. Nos topics teñen sentido pero nos outros valores non. Tería que ser algo máis así:

```yaml
title: "Nome do proxecto"
description: "Descripción do proxecto"
author: "Autor ou autora"
contact: "mail"
topics:
    - topic-1
    - topic-2
channels:
    web:
        url: url_web
        rss: url_rss
    youtube: url_channel_youtube
    twitch: url_channel_twitch
    instagram: username
    twitter: username
    tiktok: username
    podcast: url_feed
    newsletter:
       url: url_newsletter
       feed: url_newsletter_feed
```
 No caso do autor, sí que podería haber varios polo que deberíamos permitir un array:

```yaml
title: "Nome do proxecto"
description: "Descripción do proxecto"
authors:
  - "Autor ou autora"
  - "Outro autor ou autora"
contact: "mail"
topics:
    - topic-1
    - topic-2
channels:
    web:
        url: url_web
        rss: url_rss
    youtube: url_channel_youtube
    twitch: url_channel_twitch
    instagram: username
    twitter: username
    tiktok: username
    podcast: url_feed
    newsletter:
       url: url_newsletter
       feed: url_newsletter_feed
```
